(()=>{
'use strict';
const canvas=document.getElementById('adventureCanvas');
if(!canvas)return;
const ctx=canvas.getContext('2d');
const root=document.documentElement;
const stationList=document.getElementById('stationList');
const progressText=document.getElementById('adventureProgress');
const adventureScore=document.getElementById('adventureScore');
const hint=document.getElementById('canvasHintText');
const modal=document.getElementById('challengeModal');
const modalBody=document.getElementById('challengeBody');
const closeModal=document.getElementById('closeChallenge');
const soundBtn=document.getElementById('soundToggle');
const resetBtn=document.getElementById('resetAdventure');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={map:null,nodes:[],player:{x:.08,y:.84,vx:0,vy:0},keys:new Set(),selected:null,near:null,completed:new Set(),score:0,particles:[],sound:false,raf:null,last:0,challenge:null,qIndex:0,qScore:0,locked:false};
const storageKey='nusantara_2d_progress_v1';
const iconCycle=['🪨','🪁','🪵','🧩','🛖','🎯','🌀','👣','🌿','🥁','⭐','🏁'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function toast(msg){window.appToast?window.appToast(msg):console.log(msg)}
function save(){localStorage.setItem(storageKey,JSON.stringify({completed:[...state.completed],score:state.score}));updateStats();}
function load(){try{const d=JSON.parse(localStorage.getItem(storageKey)||'{}');state.completed=new Set(d.completed||[]);state.score=Number(d.score)||0}catch{} updateStats();}
function updateStats(){if(progressText)progressText.textContent=`${state.completed.size}/${state.nodes.length||12}`;if(adventureScore)adventureScore.textContent=state.score;renderStationList();}
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail||'Layanan game belum siap.')}return r.json()}
function resize(){const rect=canvas.getBoundingClientRect();const dpr=Math.min(devicePixelRatio||1,2);const w=Math.max(320,Math.round(rect.width*dpr));const h=Math.round((rect.width*10/16)*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);}
function size(){return {w:canvas.width/Math.min(devicePixelRatio||1,2),h:canvas.height/Math.min(devicePixelRatio||1,2)}}
function nodePixel(n){const {w,h}=size();return{x:n.x*w,y:n.y*h}}
function drawRoundedRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawGround(w,h,t){ctx.fillStyle='#9dd9e6';ctx.fillRect(0,0,w,h);ctx.fillStyle='#a9d486';ctx.beginPath();ctx.ellipse(w*.5,h*.58,w*.56,h*.49,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8c58b';ctx.lineWidth=26;ctx.lineCap='round';ctx.beginPath();const pts=state.nodes.map(nodePixel);if(pts.length){ctx.moveTo(w*.08,h*.84);pts.forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle='#d9c58e';ctx.stroke();ctx.lineWidth=5;ctx.strokeStyle='rgba(255,255,255,.4)';ctx.stroke()}ctx.fillStyle='#6dac68';for(let i=0;i<8;i++){const x=(i*.137*w+40)%w,y=h*(.1+.1*(i%5));ctx.beginPath();ctx.arc(x,y,11+(i%3)*3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6e5133';ctx.fillRect(x-2,y+8,4,12);ctx.fillStyle='#6dac68'}if(!reduced){ctx.globalAlpha=.7;ctx.fillStyle='#fff';for(let i=0;i<3;i++){const x=((t*.012+i*260)%(w+180))-90,y=38+i*31;ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.arc(x+20,y-6,21,0,Math.PI*2);ctx.arc(x+43,y,14,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}}
function drawBooth(n,i,t){const p=nodePixel(n),done=state.completed.has(n.id),near=state.near?.id===n.id;ctx.save();ctx.translate(p.x,p.y);if(near){ctx.fillStyle='rgba(239,185,79,.25)';ctx.beginPath();ctx.arc(0,0,31+Math.sin(t*.006)*3,0,Math.PI*2);ctx.fill()}ctx.fillStyle=done?'#236b4a':'#fff7db';ctx.strokeStyle=near?'#e36d52':'#755233';ctx.lineWidth=near?3:2;ctx.beginPath();ctx.roundRect(-24,-19,48,38,8);ctx.fill();ctx.stroke();ctx.fillStyle=done?'#174c37':'#c96049';ctx.beginPath();ctx.moveTo(-29,-18);ctx.lineTo(0,-40);ctx.lineTo(29,-18);ctx.closePath();ctx.fill();ctx.fillStyle=done?'white':'#13231c';ctx.font='18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(done?'★':iconCycle[i%iconCycle.length],0,1);ctx.fillStyle='rgba(19,35,28,.9)';ctx.font='700 11px system-ui';const label=n.name.length>18?n.name.slice(0,17)+'…':n.name;ctx.fillText(label,0,33);ctx.restore()}
function drawPlayer(t){const {w,h}=size(),x=state.player.x*w,y=state.player.y*h;ctx.save();ctx.translate(x,y);const bob=reduced?0:Math.sin(t*.012)*2;ctx.fillStyle='rgba(0,0,0,.15)';ctx.beginPath();ctx.ellipse(0,16,15,5,0,0,Math.PI*2);ctx.fill();ctx.translate(0,bob);ctx.fillStyle='#efb94f';ctx.beginPath();ctx.arc(0,-10,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#236b4a';ctx.beginPath();ctx.roundRect(-10,-2,20,23,7);ctx.fill();ctx.fillStyle='#17382a';ctx.fillRect(-8,18,6,13);ctx.fillRect(2,18,6,13);ctx.fillStyle='#13231c';ctx.beginPath();ctx.arc(-3,-11,1.2,0,Math.PI*2);ctx.arc(3,-11,1.2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawParticles(dt){for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.00025*dt}state.particles=state.particles.filter(p=>p.life>0);ctx.save();ctx.font='18px system-ui';for(const p of state.particles){ctx.globalAlpha=clamp(p.life/800,0,1);ctx.fillText('★',p.x,p.y)}ctx.restore();ctx.globalAlpha=1}
function movement(dt){let dx=0,dy=0;for(const k of state.keys){if(k==='ArrowLeft'||k==='a')dx--;if(k==='ArrowRight'||k==='d')dx++;if(k==='ArrowUp'||k==='w')dy--;if(k==='ArrowDown'||k==='s')dy++}if(dx||dy){const len=Math.hypot(dx,dy)||1;const speed=.00028*dt;state.player.x=clamp(state.player.x+dx/len*speed,.035,.965);state.player.y=clamp(state.player.y+dy/len*speed,.08,.92)}let best=null,bestD=Infinity;for(const n of state.nodes){const d=Math.hypot(state.player.x-n.x,state.player.y-n.y);if(d<bestD){best=n;bestD=d}}state.near=bestD<.085?best:null;hint.textContent=state.near?`Dekat ${state.near.name} — tekan Enter / tombol Main Pos`:'Gerakkan karakter dengan tombol panah / WASD, atau pilih pos dari daftar.';}
function frame(ts){resize();const dt=Math.min(40,ts-state.last||16);state.last=ts;movement(dt);const {w,h}=size();drawGround(w,h,ts);state.nodes.forEach((n,i)=>drawBooth(n,i,ts));drawPlayer(ts);drawParticles(dt);state.raf=requestAnimationFrame(frame)}
function renderStationList(){if(!stationList)return;stationList.innerHTML=state.nodes.map((n,i)=>`<button type="button" class="station-btn ${state.completed.has(n.id)?'done':''}" data-id="${esc(n.id)}"><span class="station-icon">${state.completed.has(n.id)?'★':iconCycle[i%iconCycle.length]}</span><span><b>${esc(n.name)}</b><small>${esc(n.region_context)}</small></span><span class="star">${state.completed.has(n.id)?'✓':n.difficulty}</span></button>`).join('');stationList.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>focusStation(b.dataset.id,true)))}
function focusStation(id,start=false){const n=state.nodes.find(x=>x.id===id);if(!n)return;state.player.x=clamp(n.x-.065,.04,.94);state.player.y=n.y;state.selected=n;if(start)setTimeout(()=>startChallenge(n),100)}
function audio(ok=true){if(!state.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=ok?660:190;g.gain.value=.04;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.12);o.onended=()=>ac.close()}catch{}}
async function startChallenge(node=state.near){if(!node)return toast('Dekati atau pilih salah satu pos permainan.');try{modal.classList.add('show');modal.setAttribute('aria-hidden','false');modalBody.innerHTML='<div class="reward"><span class="bigstar">⏳</span><h3>Menyiapkan tantangan…</h3></div>';state.challenge=await api(`/api/game/adventure/${encodeURIComponent(node.id)}`,{method:'POST',body:JSON.stringify({count:3,seed:Date.now()%1000000})});state.qIndex=0;state.qScore=0;state.locked=false;renderChallenge()}catch(e){modalBody.innerHTML=`<div class="reward"><h3>Belum bisa memulai</h3><p>${esc(e.message)}</p></div>`}}
function renderChallenge(){const d=state.challenge,q=d?.questions?.[state.qIndex];if(!q){finishChallenge();return}state.locked=false;modalBody.innerHTML=`<div class="challenge-head"><div><span class="badge">Pos ${state.qIndex+1}/${d.questions.length}</span><h3>${esc(d.game.name)}</h3><p>${esc(d.game.region_context)}</p></div></div><div class="question-card"><strong>${esc(q.prompt)}</strong><div class="context">${esc(q.context)}</div><div class="options">${q.options.map(o=>`<button type="button" class="option" data-value="${esc(o.value)}">${esc(o.label)}</button>`).join('')}</div><div id="adFeedback" class="feedback" aria-live="polite"></div><div class="challenge-actions"><button type="button" id="adNext" class="btn btn-primary" style="display:none">Lanjut</button></div></div>`;modalBody.querySelectorAll('.option').forEach(b=>b.addEventListener('click',()=>answerChallenge(b,q)));const next=document.getElementById('adNext');if(next)next.addEventListener('click',()=>{state.qIndex++;renderChallenge()})}
function answerChallenge(btn,q){if(state.locked)return;state.locked=true;const val=btn.dataset.value,ok=val===q.answer;modalBody.querySelectorAll('.option').forEach(b=>{if(b.dataset.value===q.answer)b.classList.add('correct');else if(b===btn)b.classList.add('wrong');b.disabled=true});if(ok){state.qScore++;state.score+=120;audio(true)}else audio(false);const f=document.getElementById('adFeedback');f.classList.add('show');f.innerHTML=`<strong>${ok?'Benar!':'Belum tepat.'}</strong> ${esc(q.explanation||'')}`;document.getElementById('adNext').style.display='inline-block'}
function finishChallenge(){const game=state.challenge.game,passed=state.qScore>=Math.ceil(state.challenge.questions.length*.66);if(passed){state.completed.add(game.id);state.score+=250;const {w,h}=size();for(let i=0;i<18;i++)state.particles.push({x:state.player.x*w,y:state.player.y*h,vx:(Math.random()-.5)*.12,vy:-Math.random()*.12-.03,life:700+Math.random()*500});audio(true);save()}modalBody.innerHTML=`<div class="reward"><span class="bigstar">${passed?'⭐':'🌱'}</span><h3>${passed?'Pos berhasil ditaklukkan!':'Hampir berhasil!'}</h3><p>Kamu menjawab benar ${state.qScore} dari ${state.challenge.questions.length} soal.</p><div style="display:flex;gap:9px;justify-content:center;flex-wrap:wrap"><button type="button" id="retryPos" class="btn btn-primary">${passed?'Main lagi':'Coba lagi'}</button><button type="button" id="closeReward" class="btn btn-secondary">Kembali ke arena</button></div></div>`;document.getElementById('retryPos').addEventListener('click',()=>startChallenge(state.nodes.find(n=>n.id===game.id)));document.getElementById('closeReward').addEventListener('click',hideModal);updateStats()}
function hideModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');state.challenge=null}
function bindPad(){document.querySelectorAll('[data-move]').forEach(b=>{const key=b.dataset.move;const down=e=>{e.preventDefault();state.keys.add(key)};const up=e=>{e.preventDefault();state.keys.delete(key)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)})}
async function boot(){load();try{state.map=await api('/api/game/adventure-map');state.nodes=state.map.nodes||[];updateStats();renderStationList();if(state.nodes[0])state.selected=state.nodes[0]}catch(e){toast(e.message);hint.textContent='Arena belum dapat dimuat.'}resize();frame(performance.now())}
window.addEventListener('keydown',e=>{if(modal.classList.contains('show')){if(e.key==='Escape')hideModal();return}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','w','a','s','d'].includes(e.key)){e.preventDefault();state.keys.add(e.key)}if(e.key==='Enter'&&state.near){e.preventDefault();startChallenge(state.near)}});window.addEventListener('keyup',e=>state.keys.delete(e.key));canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/(r.height||1);let best=null,dist=.12;for(const n of state.nodes){const d=Math.hypot(x-n.x,y-n.y);if(d<dist){dist=d;best=n}}if(best)focusStation(best.id,true)});closeModal.addEventListener('click',hideModal);modal.addEventListener('pointerdown',e=>{if(e.target===modal)hideModal()});document.getElementById('startNearby').addEventListener('click',()=>startChallenge(state.near||state.selected||state.nodes[0]));soundBtn.addEventListener('click',()=>{state.sound=!state.sound;soundBtn.textContent=state.sound?'🔊 Suara aktif':'🔇 Suara mati';if(state.sound)audio(true)});resetBtn.addEventListener('click',()=>{if(confirm('Reset seluruh progres petualangan 2D di browser ini?')){state.completed.clear();state.score=0;save();toast('Progres 2D direset.')}});bindPad();boot();
})();
